server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment # 项目名,也是注册的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: Admin.1324

eureka:
  client:
    # 注册进 Eureka 的服务中心
    register-with-eureka: true
    # 检索 服务中心 的其它服务
    fetch-registry: true
    service-url:
      # 设置与 Eureka Server 交互的地址
      # 单机版
      defaultZone: http://eureka7001.com:7001/eureka/